### ISSUE TITLE
Compiler warnings for missing return statement in Color.h

### ISSUE THREAD

**Issue by cyberman54** [RoboticsBrno/SmartLeds#12]
With Color.h i get two compiler warnings concerning missing return statements. Not sure if this may cause problems, the software is running for me.

Line 15
`Rgb& operator=( Rgb r ) { swap( r ); }`

> no return statement in function returning non-void [-Wreturn-type]

Line 52
 `Hsv& operator=( Hsv h ) { swap( h ); }`

> no return statement in function returning non-void [-Wreturn-type]

**Comment by yaqwsx** [comment]
Thank you for reporting the problem. The warnings were fixed, the new version should get to the PlatformIO repository in a few hours.
