### ISSUE TITLE
No output on gpio

### ISSUE THREAD

**Issue by thomasahlendorf** [RoboticsBrno/SmartLeds#2]
I try the example code on a Nodemcu-32s with a Wrooom32 modul. There was no output, but the RTM seemed to be working (added gpio signals watched with oscilloscope).

Finally, the issue was, that "gpio_set_direction" (Smartleds.h,113) modifyes (recently?) the pin-matrix set one line before - so line 112 becomes ineffective. 

Switching Line 113 and 112 will fix the problem.

**Comment by yaqwsx** [comment]
Could you open a PR for that, please?
