### ISSUE TITLE
compile error in arduino 

### ISSUE THREAD

**Issue by plankatron** [RoboticsBrno/SmartLeds#4]
WARNING: library SmartLeds-master claims to run on (espressif32) architecture(s) and may be incompatible with your current board which runs on (esp32) architecture(s).
In file included from /home/fleeky/Arduino/sketch_jan18a/sketch_jan18a.ino:2:0:
/home/fleeky/Arduino/libraries/SmartLeds-master/src/SmartLeds.h: In member function 'void Apa102::startTransmission()':
/home/fleeky/Arduino/libraries/SmartLeds-master/src/SmartLeds.h:363:32: error: 'spi_transaction_t {aka struct spi_transaction_t}' has no member named 'command'
             _transactions[ i ].command = 0;
                                ^
/home/fleeky/Arduino/libraries/SmartLeds-master/src/SmartLeds.h:364:32: error: 'spi_transaction_t {aka struct spi_transaction_t}' has no member named 'address'
             _transactions[ i ].address = 0;
                                ^
exit status 1
Error compiling for board Node32s.

**Comment by yaqwsx** [comment]
Solved via IRC discussion.
